SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS;


SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
ORDER BY event_timestamp DESC
LIMIT 1000;


SELECT * FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.LOGIN_HISTORY
    (time_range_start => DATEADD('hours', -1, CURRENT_TIMESTAMP()),
    result_limit => 1000))
ORDER BY event_timestamp DESC;


