SHOW PARAMETERS LIKE 'NETWORK_POLICY' IN ACCOUNT;

CREATE NETWORK POLICY ACCOUNT_NETWORK_POLICY
    ALLOWED_IP_LIST = ('74.199.158.166/24')
    BLOCKED_IP_LIST = ('192.168.1.0/24', '10.0.0.0/8');

SHOW NETWORK POLICIES;

DESCRIBE NETWORK POLICY ACCOUNT_NETWORK_POLICY;

ALTER ACCOUNT SET NETWORK_POLICY = 'ACCOUNT_NETWORK_POLICY';

-- Unset the network policy before dropping it
ALTER ACCOUNT UNSET NETWORK_POLICY;

DROP NETWORK POLICY ACCOUNT_NETWORK_POLICY;