-- role compounding
USE role securityadmin;
CREATE USER manager_northamerica PASSWORD = 'manager_northamerica' COMMENT = 'User for NA data' DEFAULT_WAREHOUSE = 'COMPUTE_WH' DEFAULT_NAMESPACE = 'SNOWPRO_COURSE' MUST_CHANGE_PASSWORD = FALSE;

CREATE ROLE NORTH_AMERICA_READER;

GRANT ROLE USA_READER TO ROLE NORTH_AMERICA_READER;
GRANT ROLE CANADA_READER TO ROLE NORTH_AMERICA_READER;

GRANT ROLE NORTH_AMERICA_READER TO USER manager_northamerica;

ALTER USER manager_northamerica SET DEFAULT_ROLE='NORTH_AMERICA_READER';

SHOW GRANTS TO ROLE NORTH_AMERICA_READER;
SHOW GRANTS OF ROLE NORTH_AMERICA_READER;

-- run on another window with the manager_northamerica
SELECT current_user();

USE ROLE USA_READER;

USE DATABASE SNOWPRO_COURSE;

USE WAREHOUSE COMPUTE_WH;

USE SCHEMA USA;

SELECT * FROM USA_SALES;

USE SCHEMA CANADA;

USE ROLE CANADA_READER;

USE SCHEMA CANADA;

SELECT * FROM CANADA_SALES;

SELECT CURRENT_ROLE();

-- run on another window with manager_one
-- primary and secondary roles
SELECT current_user();

USE ROLE USA_READER;

USE DATABASE SNOWPRO_COURSE;

USE SCHEMA USA;

SELECT * FROM USA_SALES;

USE SCHEMA CANADA;

USE SECONDARY ROLES ALL;

SELECT * FROM CANADA.CANADA_SALES;

SELECT * FROM USA.USA_SALES;

SELECT CURRENT_ROLE();
SELECT CURRENT_SECONDARY_ROLES();