USE ROLE SYSADMIN;

CREATE DATABASE SNOWPRO_COURSE;

USE DATABASE SNOWPRO_COURSE;

CREATE SCHEMA CANADA;

CREATE TABLE CANADA.CANADA_SALES (
    city VARCHAR,
    sales INTEGER
    );

INSERT INTO CANADA.CANADA_SALES (city, sales) VALUES
    ('Toronto', 10000000),
    ('Montreal', 7000000),
    ('Vancouver', 5000000),
    ('Ottawa', 1000000);

CREATE SCHEMA USA;
  
CREATE TABLE USA.USA_SALES (
    city VARCHAR,
    sales INTEGER
    );

INSERT INTO USA.USA_SALES (city, sales) VALUES
    ('New York', 10000000),
    ('Chicago', 7000000),
    ('Los Angeles', 5000000),
    ('Miami', 1000000);
    
USE ROLE SECURITYADMIN;

CREATE USER manager_one PASSWORD = 'manager_one' COMMENT = 'User for USA and Canada data' DEFAULT_WAREHOUSE = 'COMPUTE_WH' DEFAULT_NAMESPACE = 'SNOWPRO_COURSE' MUST_CHANGE_PASSWORD = FALSE;

-- create a role for the USA data only
CREATE ROLE "USA_READER";

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE USA_READER;
GRANT USAGE ON DATABASE SNOWPRO_COURSE TO ROLE USA_READER;
GRANT USAGE ON SCHEMA SNOWPRO_COURSE.USA TO ROLE USA_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWPRO_COURSE.USA TO ROLE USA_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWPRO_COURSE.USA TO ROLE USA_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SNOWPRO_COURSE.USA TO ROLE USA_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SNOWPRO_COURSE.USA TO ROLE USA_READER;

GRANT ROLE USA_READER TO USER manager_one;

ALTER USER manager_one SET DEFAULT_ROLE='USA_READER';

SHOW GRANTS TO ROLE USA_READER;
SHOW GRANTS OF ROLE USA_READER;


-- create a role for the Canada data only
CREATE ROLE "CANADA_READER";

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE CANADA_READER;
GRANT USAGE ON DATABASE SNOWPRO_COURSE TO ROLE CANADA_READER;
GRANT USAGE ON SCHEMA SNOWPRO_COURSE.CANADA TO ROLE CANADA_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWPRO_COURSE.CANADA TO ROLE CANADA_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWPRO_COURSE.CANADA TO ROLE CANADA_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SNOWPRO_COURSE.CANADA TO ROLE CANADA_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SNOWPRO_COURSE.CANADA TO ROLE CANADA_READER;

GRANT ROLE CANADA_READER TO USER manager_one;

SHOW GRANTS TO ROLE CANADA_READER;
SHOW GRANTS OF ROLE CANADA_READER;

-- now try to use these roles with the manager_one user!